name: chatty_v
favicon: null
layout_spectrum: 0.5340144883375615
typography_spectrum: 0.25811689090915024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.8955263416282833
  saturation: 0.5
  rhythmicContrast: 0.3653275116812438
purpose: []
